apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  replicas: 4
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: app
          image: courselabs/whoami-lab:21.09-3